# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

title: Davide's GitHub pages
description: Sporadic posts on GitHub pages
github_username: davidefiocco

# Email and twitter are optional:
email:
twitter_username: monodavide

# Set this to true to get LaTeX math equation support
use_math: true

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-octicons
  - jekyll-github-metadata
  - jekyll-include-cache

remote_theme: "mmistakes/minimal-mistakes@4.21.0"